// generated by Fast Light User Interface Designer (fluid) version 1.0308

#pragma once

#include <FL/Fl.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Text_Display.H>

class StoreGroup : public Fl_Group {
public:
  StoreGroup(int X, int Y, int W, int H, const char *L = 0);

private:
  Fl_Output *priceLabel;
  Fl_Output *statusLabel;

public:
  Fl_Text_Display *description;
};
