// generated by Fast Light User Interface Designer (fluid) version 1.0308

#pragma once

#include <FL/Fl_Output.H>
#include <FL/Fl_Text_Display.H>

#include "UI/Tab.hh"

class StoreTab : public Tab {
public:
  StoreTab(const StoreTab &) = delete;
  StoreTab &operator=(const StoreTab &) = delete;
  virtual ~StoreTab() = default;

  StoreTab(State &s);

private:
  Fl_Output *priceLabel;
  Fl_Output *statusLabel;
  Fl_Text_Display *description;
};
